targets:
  - 'labels'
  - 'evaluations'
input_data_file: 'test_input.txt'
param_labels: []
run_label: 'test'
read_csv_kwargs: {}
evaluations: ['silhouette', 'calinskiharabasz', 'daviesbouldin']
eval_kwargs: {}
clustering_addtl_kwargs: {}
generate_parameters_addtl_kwargs: {'random_search':false}
clusterer_kwargs: {}
param_sets: {}
param_sets_labels: []
optimization_parameters:
  affinitypropagation:
    damping:
    - 0.8
    - 0.85
    - 0.9
  hdbscan:
    min_cluster_size: &id002
    - 6
    - 8
    - 10
    - 12
  kmeans:
    n_clusters: &id001
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
  minibatchkmeans:
    n_clusters: *id001
  optics:
    min_samples: *id002
