intermediates_folder: 'clustering_intermediates'
clustering_results: 'clustering'
gold_standard_file: 'gold_standard_file.txt'

input_data_folder: '.'
input_data_file: ['test_input']
targets: ['labels', 'evaluations']

run_label: 'test'
read_csv_kwargs: {'index_col':0}
evaluations: ['silhouette', 'calinskiharabasz', 'daviesbouldin']
eval_kwargs: {}
clustering_addtl_kwargs: {}
generate_parameters_addtl_kwargs: {'random_search':false}
clusterer_kwargs: {}

optimization_parameters:
  affinitypropagation:
    damping:
    - 0.8
    - 0.85
    - 0.9
  hdbscan:
    min_cluster_size: &id002
    - 6
    - 8
    - 10
    - 12
  kmeans:
    n_clusters: &id001
    - 4
    - 5
    - 6
    - 7
    - 8
  minibatchkmeans:
    n_clusters: *id001
  optics:
    min_samples: *id002
