clusterer_kwargs: {}
clustering_results: clustering
eval_kwargs: {}
evaluations:
- adjusted_rand_score
- adjusted_mutual_info_score
- homogeneity_score
- completeness_score
- fowlkes_mallows_score
- mutual_info_score
- v_measure_score
- silhouette_score
- calinski_harabasz_score
- davies_bouldin_score
- number_clustered
- smallest_largest_clusters_ratio
- smallest_cluster_ratio
generate_parameters_addtl_kwargs:
  random_search: false
gold_standards:
  sc_data: gold_standard.csv
heatmap_kwargs: {}
input_data_files:
- sc_data
input_data_folder: /gpfs/data/ruggleslab/home/lmb529/hypercluster/examples/scRNA_seq
intermediates_folder: clustering_intermediates
make_label_fig: true
make_sample_fig: false
metric_to_choose_best: silhouette_score
metric_to_compare_labels: adjusted_rand_score
optimization_parameters:
  AffinityPropagation:
    damping:
    - 0.55
    - 0.6
    - 0.65
    - 0.7
    - 0.75
    - 0.8
    - 0.85
    - 0.9
    - 0.95
  HDBSCAN:
    min_cluster_size: &id002
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
  KMeans:
    n_clusters: &id001
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
    - 45
    - 46
    - 47
    - 48
    - 49
    - 50
    - 51
    - 52
    - 53
    - 54
    - 55
    - 56
    - 57
    - 58
    - 59
  MiniBatchKMeans:
    n_clusters: *id001
  OPTICS:
    min_samples: *id002
output_kwargs:
  evaluations:
    index_col:
    - 0
  labels:
    index_col:
    - 0
read_csv_kwargs:
  sc_data:
    index_col:
    - 0
targets:
- labels
- evaluations
