clusterer_kwargs: {}
clustering_results: clustering
compare_samples: false
eval_kwargs: {}
evaluations:
- adjusted_mutual_info_score
- adjusted_rand_score
- calinski_harabasz_score
- completeness_score
- davies_bouldin_score
- fowlkes_mallows_score
- homogeneity_score
- largest_cluster_size
- mutual_info_score
- number_of_clusters
- silhouette_score
- smallest_cluster_size
- smallest_largest_clusters_ratio
- v_measure_score
generate_parameters_addtl_kwargs: {}
gold_standards:
  sc_data: gold_standard.csv
heatmap_kwargs: {}
input_data_files:
- sc_data
input_data_folder: /gpfs/data/ruggleslab/home/lmb529/hypercluster/examples/snakemake_scRNA_example
intermediates_folder: clustering_intermediates
metric_to_choose_best: adjusted_rand_score
metric_to_compare_labels: adjusted_rand_score
optimization_parameters:
  AffinityPropagation:
    damping:
    - 0.55
    - 0.6
    - 0.65
    - 0.7
    - 0.75
    - 0.8
    - 0.85
    - 0.9
    - 0.95
  HDBSCAN:
    min_cluster_size: &id003
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
  KMeans:
    n_clusters: &id002
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
  LeidenCluster: &id001
    k:
    - 20
    - 30
    - 40
    - 80
    - 120
    resolution:
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    - 1.0
    - 1.2
    - 1.4
    - 1.6
  LouvainCluster: *id001
  MiniBatchKMeans:
    n_clusters: *id002
  NMFCluster:
    n_clusters: *id002
  OPTICS:
    min_samples: *id003
output_folder: results
output_kwargs:
  evaluations:
    index_col:
    - 0
  labels:
    index_col:
    - 0
read_csv_kwargs:
  sc_data:
    index_col:
    - 0
screeplot_evals:
- adjusted_mutual_info_score
- adjusted_rand_score
- calinski_harabasz_score
- completeness_score
- davies_bouldin_score
- fowlkes_mallows_score
- homogeneity_score
- largest_cluster_size
- mutual_info_score
- number_of_clusters
- silhouette_score
- smallest_cluster_size
- smallest_largest_clusters_ratio
- v_measure_score
